version: '3'
services:
  postgres:
    image: postgres:10
    ports: ['127.0.0.1:5432:5432']
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yara
    expose:
      - "5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1', 'ELASTIC_PASSWORD=abcd']
    ports: ['127.0.0.1:9200:9200']

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=abcd
    ports: ['127.0.0.1:5601:5601']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.4
    container_name: logstash
    environment:
      - 'xpack.monitoring.elasticsearch.password=abcd'
    # Provide a simple pipeline configuration for Logstash with a bind-mounted file.
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./config/postgresql-42.2.2.jar:/usr/share/logstash/plugins/postgresql-42.2.2.jar
    depends_on: ['postgres', 'elasticsearch']
    # command: bash -c "logstash-plugin install logstash-input-jdbc && logstash"
