# Generated by Django 2.0.4 on 2018-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(auto_now=True)),
                ('readable_source', models.TextField()),
                ('source', models.SlugField()),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('img', models.URLField()),
                ('categories', models.ManyToManyField(to='recipes.Category')),
            ],
            options={
                'ordering': ('last_updated', 'source'),
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='recipes_cat_slug_178eca_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['source'], name='recipes_rec_source_b6db08_idx'),
        ),
    ]
