# Generated by Django 2.0.4 on 2018-04-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_hash',
            field=models.CharField(max_length=32),
        ),
    ]
