# Generated by Django 2.0.4 on 2018-04-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180422_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
